//
// Generated by LLVM NVPTX Back-End
//

.version 3.2
.target sm_20, texmode_independent
.address_size 64

	// .globl	vector_square

.entry vector_square(
	.param .u64 .ptr .global .align 16 vector_square_param_0,
	.param .u64 .ptr .global .align 16 vector_square_param_1
)
{
	.reg .f32 	%f<9>;
	.reg .s32 	%r<6>;
	.reg .s64 	%rd<7>;

	ld.param.u64 	%rd2, [vector_square_param_1];
	ld.param.u64 	%rd1, [vector_square_param_0];
	mov.u32	%r1, %ctaid.x;
	mov.u32	%r2, %ntid.x;
	mul.lo.s32 	%r3, %r2, %r1;
	mov.u32	%r4, %tid.x;
	add.s32 	%r5, %r3, %r4;
	cvt.s64.s32	%rd3, %r5;
	shl.b64 	%rd4, %rd3, 4;
	add.s64 	%rd5, %rd1, %rd4;
	ld.global.v4.f32 	{%f1, %f2, %f3, %f4}, [%rd5];
	mul.rn.f32 	%f5, %f4, %f4;
	mul.rn.f32 	%f6, %f3, %f3;
	mul.rn.f32 	%f7, %f2, %f2;
	mul.rn.f32 	%f8, %f1, %f1;
	add.s64 	%rd6, %rd2, %rd4;
	st.global.v4.f32 	[%rd6], {%f8, %f7, %f6, %f5};
	ret;
}


